// <auto-generated />
using System;
using CreditCase.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CreditCase.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CreditCase.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime?>("DeletedAt").HasColumnType("datetime2");
                    b.Property<DateTime>("DateOfBirth").HasColumnType("datetime2");
                    b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("EmploymentStatus").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("IdentityNumber").IsRequired().HasMaxLength(11).HasColumnType("nvarchar(11)");
                    b.Property<int>("CreditScoreBonus").HasDefaultValue(0).HasColumnType("int");
                    b.Property<bool>("IsDeleted").HasDefaultValue(false).HasColumnType("bit");
                    b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<decimal>("MonthlyIncome").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                    b.Property<string>("PhoneNumber").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<string>("ProfessionCategory").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique().HasFilter("[IsDeleted] = 0");
                    b.HasIndex("IdentityNumber").IsUnique().HasFilter("[IsDeleted] = 0");
                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CreditCase.Domain.Entities.Installment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                    b.Property<DateTime>("DueDate").HasColumnType("datetime2");
                    b.Property<int>("InstallmentNumber").HasColumnType("int");
                    b.Property<bool>("IsBalloon").HasDefaultValue(false).HasColumnType("bit");
                    b.Property<int>("LoanId").HasColumnType("int");
                    b.Property<string>("Status").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("LoanId");
                    b.ToTable("Installments");
                });

            modelBuilder.Entity("CreditCase.Domain.Entities.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("CustomerId").HasColumnType("int");
                    b.Property<decimal>("InterestRate").HasPrecision(5, 2).HasColumnType("decimal(5,2)");
                    b.Property<string>("LoanType").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<decimal>("PrincipalAmount").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                    b.Property<decimal>("RemainingPrincipal").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                    b.Property<DateTime>("StartDate").HasColumnType("datetime2");
                    b.Property<string>("Status").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("Term").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("CustomerId");
                    b.ToTable("Loans");
                });

            modelBuilder.Entity("CreditCase.Domain.Entities.LoanEvaluationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<decimal>("ApprovedAmount").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                    b.Property<decimal>("ApprovedInterestRate").HasPrecision(5, 2).HasColumnType("decimal(5,2)");
                    b.Property<int>("CreditScore").HasColumnType("int");
                    b.Property<int>("CustomerId").HasColumnType("int");
                    b.Property<DateTime?>("DeletedAt").HasColumnType("datetime2");
                    b.Property<decimal>("DebtToIncomeRatio").HasPrecision(5, 4).HasColumnType("decimal(5,4)");
                    b.Property<DateTime>("EvaluationDate").HasColumnType("datetime2");
                    b.Property<DateTime>("ExpirationDate").HasColumnType("datetime2");
                    b.Property<bool>("IsApproved").HasColumnType("bit");
                    b.Property<bool>("IsDeleted").HasDefaultValue(false).HasColumnType("bit");
                    b.Property<decimal>("MaximumAmount").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                    b.Property<int>("MaximumTerm").HasColumnType("int");
                    b.Property<decimal>("MonthlyInstallmentEstimate").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                    b.Property<string>("RejectionReason").HasColumnType("nvarchar(max)");
                    b.Property<decimal>("RequestedAmount").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                    b.Property<string>("RequestedLoanType").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("RequestedTerm").HasColumnType("int");
                    b.Property<string>("RiskLevel").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("CustomerId");
                    b.ToTable("LoanEvaluations");
                });

            modelBuilder.Entity("CreditCase.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("InstallmentId").HasColumnType("int");
                    b.Property<decimal>("PaymentAmount").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                    b.Property<DateTime>("PaymentDate").HasColumnType("datetime2");
                    b.Property<string>("Status").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("InstallmentId").IsUnique();
                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CreditCase.Domain.Entities.Installment", b =>
                {
                    b.HasOne("CreditCase.Domain.Entities.Loan", "Loan")
                        .WithMany("Installments")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Loan");
                });

            modelBuilder.Entity("CreditCase.Domain.Entities.Loan", b =>
                {
                    b.HasOne("CreditCase.Domain.Entities.Customer", "Customer")
                        .WithMany("Loans")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CreditCase.Domain.Entities.LoanEvaluationResult", b =>
                {
                    b.HasOne("CreditCase.Domain.Entities.Customer", "Customer")
                        .WithMany("LoanEvaluations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CreditCase.Domain.Entities.Payment", b =>
                {
                    b.HasOne("CreditCase.Domain.Entities.Installment", "Installment")
                        .WithOne("Payment")
                        .HasForeignKey("CreditCase.Domain.Entities.Payment", "InstallmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Installment");
                });

            modelBuilder.Entity("CreditCase.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Loans");
                    b.Navigation("LoanEvaluations");
                });

            modelBuilder.Entity("CreditCase.Domain.Entities.Installment", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("CreditCase.Domain.Entities.Loan", b =>
                {
                    b.Navigation("Installments");
                });
#pragma warning restore 612, 618
        }
    }
}
